main: com.theendlessweb.electromaster.Main
name: CustomCommands
version: 1.0
author: xxq/Electromaster
description: The custom commands plugin created for FireSurvival
commands:
  supertnt:
    description: Super TNT
    usage: /mycommand
    permission: customcommands.supertnt
    permission-message: You don't have the required permission node. Contact staff if you believe this is in error.
  
