main: com.theendlessweb.electromaster.Main
name: CustomCommands
version: 1.0
author: xxq/Electromaster
description: The custom commands plugin created for FireSurvival
commands:
  supertnt:
    description: Super TNT
    usage: /supertnt
    permission: customcommands.supertnt
    permission-message: You don't have the required permission node. Contact staff if you believe this is in error.
  sword:
    description: Get Electromaster's God Sword
    usage: /sword
    permission: customcommands.sword
    permission-message: You don't have the required permission node. Contact staff if you believe this is in error.
  eat:
    description: Fill ye hungah.
    usage: /eat
    permission: customcommands.eat
    permission-message: You don't have the required permission node. Contact staff if you believe this is in error.
  
