main: com.theendlessweb.electromaster.Main
name: CustomCommands
version: 1.24
author: xxq/Electromaster
description: A plugin designed to provide simple item commands for efficiency.
commands:
  supertnt:
    description: Super TNT
    usage: Usage: /supertnt
    permission: customcommands.supertnt
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  tools:
    description: Get God Tools
    usage: Usage: /tools
    permission: customcommands.sword
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  eat:
    description: Fills hunger/saturation/health.
    usage: Usage: /eat
    permission: customcommands.eat
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  axe:
    description: Gives an axe with level 32767 enchantments
    usage: Usage: /axe
    permission: customcommands.axe
    permission-message: You don't have the required permission node. Contact staff is you believe this is an error.
  armor:
    description: Get God Armor
    usage: Usage: /armor
    permission: customcommands.armor
    permission-message: You don't have the required permmission node. Contact staff is you believe this is an error.
  flight:
    description: Gives you Elytra with Fireworks
    usage: Usage: /flight
    permission: customcommands.flight
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  sclean:
    description: Cleans illegal items from online player's inventories and enderchests
    usage: Usage: /sclean
    permission: customcommands.sclean
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  copy:
    description: Copies the item in your hand the num. of times you specify.
    usage: Usage: /copy <amount>
    permission: customcommands.copy
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  magicskull:
    description: Gives you a magical copy of your skull.
    usage: Usage: /magicskull
    permission: customcommands.magic
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
