main: com.theendlessweb.electromaster.Main
name: CustomCommands
version: 1.0
author: xxq/Electromaster
description: A plugin designed to give simple item features and other simple features.
commands:
  supertnt:
    description: Super TNT
    usage: /supertnt
    permission: customcommands.supertnt
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  tools:
    description: Get God Tools
    usage: /tools
    permission: customcommands.sword
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  eat:
    description: Fill ye hungah.
    usage: /eat
    permission: customcommands.eat
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
  axe:
    description: Get Electromaster's God Axe
    usage: /axe
    permission: customcommands.axe
    permission-message: You don't have the required permission node. Contact staff is you believe this is an error.
  armor:
    description: Get God Armor
    usage: /armor
    permission: customcommands.armor
    permission-message: You don't have the required permmission node. Contact staff is you believe this is an error.
  flight:
    description: Gives you Elytra with Fireworks
    usage: /flight
    permission: customcommands.flight
    permission-message: You don't have the required permission node. Contact staff if you believe this is an error.
